server:
  ssl.enabled: false
spring:
  datasource:
    url: ${PROD__SPRING__DATASOURCE__URL}
    username: ${PROD__SPRING__DATASOURCE__USERNAME}
    password: ${PROD__SPRING__DATASOURCE__PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
custom:
  security:
    cookieSecure: true