spring:
  autoconfigure:
    exclude:
  data:
    redis:
      host: redis_1
      password: ${PROD__SPRING__DATA__REDIS__PASSWORD}
  datasource:
    url: jdbc:mysql://mysql_1:3306/${PROD__SPRING__DATASOURCE__URL___DB_NAME}?rewriteBatchedStatements=true
    username: local
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
logging:
  level:
    com.back: INFO
    org.hibernate.orm.jdbc.bind: INFO
    org.hibernate.orm.jdbc.extract: INFO
    org.springframework.transaction.interceptor: INFO
custom:
  site:
    cookieDomain: "${custom.prod.cookieDomain}"
    cookieSecure: "${custom.prod.cookieSecure}"
    frontUrl: "${custom.prod.frontUrl}"
    backUrl: "${custom.prod.backUrl}"